# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20170217_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardevent',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='standardevent',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
