# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20170217_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardevent',
            name='address',
            field=models.CharField(default='27 upland road', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardevent',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=(1.0, 1.0), max_length=63),
            preserve_default=False,
        ),
    ]
