# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:04
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20170217_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('visiting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.VisitingDay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandaloneEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('coordinator', models.CharField(max_length=31)),
                ('audience', models.CharField(blank=True, choices=[('S', 'Student'), ('P', 'Parent')], max_length=1)),
                ('balloon_color', colorful.fields.RGBColorField()),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('visiting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.VisitingDay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('coordinator', models.CharField(max_length=31)),
                ('audience', models.CharField(blank=True, choices=[('S', 'Student'), ('P', 'Parent')], max_length=1)),
                ('balloon_color', colorful.fields.RGBColorField()),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('composite_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.CompositeEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='standardevent',
            name='visiting_day',
        ),
        migrations.DeleteModel(
            name='StandardEvent',
        ),
    ]
