# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(upload_to='coupons'),
        ),
    ]
